language: ruby
rvm:
- 2.2.4
deploy:
  provider: heroku
  api_key:
    secure: Y5/89NBmCsJp3JBvEPWGBK3ESo2h1mel6XP0LKjHWpIpEwbcZy5YP0bwhLJyKMeZihWnEwnnqMwbAjw8+9WJz0CvWYk7PLDtkoPFvm35D0fLxKpQXzQDEfjYXB2Ecx9FqEravSMzYJFcfUNBJRZif/9Xqh9cXTm5Yl5zmQtjo2ARPJzFzw5XeeS2BdQYRM5U+pEm23vjp7xOZZtcYhhL+6mQGPhYpa+meaTSjXWDN5fzQ5/qAbZE116kZxjio5DamKf85fARpSrKth9wM8bsJQ6YO/xL9CUg1yWZ8CmfTHzp0locDF7WvxUSNwpjDuCNZXchQ+L/YFhGL/W+mRsTbb14RNyaMG45nokAHULuGCqsOp5JtrXIHFQAUMkw/D1w/FiinnxqL8dpbxurl5r+D1neG6tl6kVUnPhZd5YDa77RI8lBR5Cdk/PH16EdG308Q/RbM4TxhBEwrZEHUoVjx9F0gCJLBaEGZNs1y09kjt1vWZj/AQwYY8kiOYWlTH9a1vkFuV7Ly6QrageIFMEmw9hH8UfaV3nCxbxh3VydX0kZV8iyvYvF4dgqjUVZyoDKUL0E94JbiiQspg01UDHqIvTWjeOAxeEW2gT7oE5bNpEvOyXMMPIBfnP91VN9+wYTJ0AJjrTx0T3JWK/iRrOsjDs4YoohkBq9wEJuMqP1uc0=
  app: agile-beyond-94050
  on:
    repo: thibaut-monrouzeau/projet
